# travis build for APhotoManager
language: android
android:
  components:
    - build-tools-23.0.1
    - android-21
    - add-on
    - extra

before_install:
# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
 - chmod +x gradlew
 
script:
  - ./gradlew assemble
